version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: oleksandrayanovych/lab4:compose-jango
    container_name: django
    networks:
      - public
    ports:
      - 8000:8000
  monitoring:
    build:
      context: .
      dockerfile: Dockerfile.site
    image: oleksandrayanovych/lab4:compose-monitoring
    container_name: monitoring
    network_mode: host

networks:
  public:
    driver: bridge
